parameters:
#    imageupload.example.class: image\uploadBundle\Example

services:
#    imageupload.example:
#        class: %imageupload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
